### ISSUE TITLE
Branchless programming

### ISSUE THREAD

**Issue by yakra** [yakra/DataProcessing#214]
From the description of [this video](https://www.youtube.com/watch?v=g-WPhYREFjk) I've only barely started watching:
> Have you ever written code like this:
void f(bool b, long x, long& s) { if (b) s += x; }

My mind instantly goes to `{ s += b*x }`. (Haha yup. And he gets to exactly that at 56:58 in the video.)
Not just C++ -- I've done this kinda thing in Python too (though not committed yet) and it did seem to help a bit:
```py
sqlfile.write("('" + r.root + "','" + t.traveler_name + "','" + str(m) + "','" + str(int(m >= r.mileage)) + "')\n")
```
## ToDo
* [ ] Actually watch the video; see what yer man has to say

**can lose if**
siteupdate.py line numbers from d56e5a67555922d06730363ca779c0acdc224dac
* [ ] 342
* [ ] 1181
* [ ] con_beg & con_end?
* [ ] 2974
* [ ] 3397
* [ ] 3624, except it conflicts with r2cr @ c8237dd
* [ ] 3636 may not by Pythonic, but think about it in C++ ;)
* [ ] 4189
* [ ] 4679
* [ ] ToDo: C++

**`+=` operator**
* [ ] 127
* [ ] 2437
* [ ] 3396
* [ ] ToDo: C++

**`|=`? `&=`?**
* [ ] nothing in Py; look in C++

---

* [ ] ternary operators (branchless? See 55:50)
* [ ] Replacing `&&` and `||` with bitwise `&` and `|`, `+`, `*` etc.
* [ ] use bool as array index

**Comment by yakra** [comment]
https://www.reddit.com/r/programming/comments/mmjrez/branchless_programming_why_if_is_sloowww_and_what/
* [ ] A couple `ToUpper` demonstrations start just before 11 mins.

**Comment by yakra** [comment]
* [ ] `li_count += li`
https://github.com/yakra/DataProcessing/blob/9dcf0a5549cc6100082710637e2653e99afd8c80/siteupdate/cplusplus/classes/Waypoint/Waypoint.cpp#L224
