### ISSUE TITLE
items allocated per thread

### ISSUE THREAD

**Issue by yakra** [yakra/DataProcessing#218]
A generalization of #217...

```sh
grep '\[Args::numthreads\]\|\[numthreads\]' `find . -name \*.cpp`
```
```c++
./classes/WaypointQuadtree/WaypointQuadtree.cpp:{	std::forward_list<WaypointQuadtree*>* nodes = new std::forward_list<WaypointQuadtree*>[Args::numthreads];
./classes/GraphGeneration/HGVertex.cpp:	s_vertex_num = new int[Args::numthreads];
./classes/GraphGeneration/HGVertex.cpp:	c_vertex_num = new int[Args::numthreads];
./classes/GraphGeneration/HGVertex.cpp:	t_vertex_num = new int[Args::numthreads];
./classes/GraphGeneration/HGEdge.cpp:	written = new char[Args::numthreads];
./classes/GraphGeneration/HGEdge.cpp:	written = new char[Args::numthreads];
./classes/TravelerList/TravelerList.cpp:	in_subgraph = new bool[Args::numthreads];
./classes/TravelerList/TravelerList.cpp:	traveler_num = new unsigned int[Args::numthreads];
./siteupdate.cpp:	list<string>* augment_lists = new list<string>[Args::numthreads];
```

* [ ] Quadtree `nodes` could be a std::vector. See #160.
* [ ] GraphGeneration & TravelerList stuff is mentioned @ #217.
* [ ] `augment_lists` [may perform better as a list, may perform better as a vector](https://github.com/yakra/DataProcessing/issues/165).
