### ISSUE TITLE
TravelerList::userlog speed ideas

### ISSUE THREAD

**Issue by yakra** [yakra/DataProcessing#234]
* [ ] [rename TravelerList::system_region_miles](https://github.com/yakra/DataProcessing/issues/228) *(not speed related; this just needs to happen)*
* [ ] remove extraneous `if` up top
* [ ] remove extraneous `if (r->last_update)`; this was checked prior to insertion
https://github.com/yakra/DataProcessing/blob/29a6edfddc1132bfac95e0bbc59157f27fade551/siteupdate/cplusplus/classes/TravelerList/userlog.cpp#L122
* [ ] save `system_region_mileages` iterator as stashed in `8ccb8b7`
* [ ] [HighwaySystem::total_mileage](https://github.com/yakra/DataProcessing/issues/233)
* [ ] Don't keep sorting `sysmbr` (AKA `HighwaySystem::mileage_by_region`) contents; replace with an ordered `map`
* [ ] These items are only used once; probably not worth it to convert to `map`:
  * [ ] `active_preview_mileage_by_region`
  * [ ] `updated_routes`
* [ ] save iterator & use ternary:
  * [ ] `t_active_miles`
  * [ ] `system_region_mileage`
* [ ] avoid std::string concatenation and extraneous malloc/free of temporaries
  * [ ] `Route::readable_name()`
  * [ ] `ConnectedRoute::readable_name()`
* [ ] `Route` objects contiguously stored in a `TMArray`
* [ ] lowest priority: [single TravelerList::mileage_by_region table](https://github.com/yakra/DataProcessing/issues/212)

**Comment by yakra** [comment]
### Bad ideas

* `for (HighwaySystem *h : HighwaySystem::syslist)`
  * [ ] `auto& region_mileages = system_region_mileages.at(h);` and put the whole "stats by system" routine in one big `try` block.
    Significantly slower. Verify that it's slower on FreeBSD too.
  * [ ] `auto it = system_region_mileages.find(h);` and then dereference, as stashed in `8ccb8b7`.
    Still a bit slower though not as much. Verify slower on FreeBSD.
* **Instead,** either:
  * [ ] Sort a list of key/value pairs
  * [ ] Make `system_region_mileages` an ordered `map`
