### ISSUE TITLE
`TMBitset` checklist

### ISSUE THREAD

**Issue by yakra** [yakra/DataProcessing#245]
**Benchmark:**
* [x] `Route::clinched_by_traveler`: branching vs indirection
  *Branching is faster.*
* [x] Graph generation with different `unit`s
  *Bigger is faster.*
* [x] Explicitly inline `matching_vertices_and_edges` (Change name? It finds travelers too)
  *Slightly faster on all machines except lab2. (Noise?)*
* [x] Try branchless variant of `eaa6`:
  ```c++
  for (size_t index = 0; index < traveler_lists.size(); ++index)
  	code[index/4] += clinched_by(traveler_lists[index]) << index%4;
  ```
  *Branching is faster.*
* [x] Revert `eaa6`; apply `4e05` directly to prev commit
  For *Computing Stats*, `96e9`...
  • is THE top performer so far for lab1, lab3, lab4.
  • outperforms `4e05` on BiggaTomato.
  • on lab2 lags behind top performer `4e05` by only 3.8 ms. Just noise? A very tight race here.
* [x] `5c76` inconclusive, but does appear slightly slower for userlogs, very consistently. Try:
  * [x] comparing against `6922` for a more apples-to-apples comparison.
  * [x] comparing against the final selected commit once all the dust settles (see `4a64`).
  * [x] Out of curiosity, is there a diff if I build with GCC instead of clang? **Yes.**
* [x] What if `traveler_lists` is nixed altogether?
  As we iterate thru `traveler_set`, just keep a count instead of creating a vector.
  The trade-off is doing one more iteration thru `traveler_set` at the end of the traveled graph for traveler names.
  Is this outweighed by not having to construct the vector and do a modest number of allocations/reallocations?
  **Preliminary results:** helps on BiggaTomato; hurts on lab1. Be interesting to see results on bsdlab, at higher thread counts, and after doing more work on the RAM bandwidth bottleneck.
  **Final:** No speed advantage. Leaving as-is. **Maybe re-examine** after more RAM bandwidth improvements are implemented.

**Try out:**
* [x] [What happens to traveled graphs if a devel system comes before concurrent a/p in systems.csv?](https://github.com/TravelMapping/DataProcessing/issues/588)
* [x] How much does initial `HGEdge` construction slow down if I force an active/preview canonical `HighwaySegment`?
  *\~ 0.01 - 0.02 s on BiggaTomato -- 0.9 - 1.9 % more time.*
* [x] Simple iteration optimization (with different `unit`s)
  The trade-off: Larger units = skip back farther but less often.
  * 64-bit is clearly suboptimal.
  * 8, 16 & 32-bit all very close to margin of error. Maybe a slight edge for 32-bit; makes sense to use it anyway because good `|=` performance.
* [x] Complex iteration optimization
  * 8-bit `f749` underperforms 8-32-bit simple iteration on lab{1..4}; slight lead on BiggaTomato.
  * 16-bit `ec4e` is 1st place for BiggaTomato & lab1; underperforms `f749` & even 64-bit `f8cf` on lab2.
  Other machines **TBD**.
    * [x] `[bits >> 1]` solution
    * [x] ternaries
      Both underperform `ec4e` on BiggaTomato & lab1. Successively better on lab2 though, with ternaries 1st place overall & `[bits >> 1]` falling between 16 & 32-bit SIO2. Other machines **TBD**.
  * [x] How much time does the 15-bit lookup table take to construct? Does this outweigh the advantage of using 16-bit ComItOpt?
    * About 0.3 ms on BiggaTomato.
    * N/A -- there *isn't* an advantage to using 16-bit ComItOpt.
  * ~LOL what if I `constexpr` the damn thing by brute force?~ Never mind. Nothing to be gained by doing this.
  * [x] 32k is 1/16 of 512k. Will `ec4e` perform poorly on Epoch? **No.** Performs well; outperforms SIO2. Similar to BiggaTomato.
* [x] Pointer punning `|=`
  Try simplified versions for larger units:
  * [x] 64-32-16-bit
  * [x] 64-16-bit
  * [x] 64-32-bit
* [x] Replace `TravelerList::traveler_num` with one
  `unsigned int* traveler_num = new unsigned int[TravelerList::allusers.size()];` per thread.
  Index via `for (TravelerList *t : traveler_lists) traveler_nums[t-TravelerList::allusers.data()] = travnum++;`
* [x] ~A variant of `eaa6` with TMBitset `[]` operator?~ LOLNOPE. Different vectors (everything vs subset); indices don't match up.

**Kinda both:**
* ~Init TravelerLists at beginning; init segments with size not capacity~
* [x] ~Or better yet, init segments with `TravelerList::ids.size()`~
  Segments set via TMArray::size, set via TravelerList::ids.size()
* [x] Timestamp for first task, with & without. Python Too?
* [x] `TMArray<TravelerList>` means threaded construction in place (via placement new) without separate read_list function.
* #251

**Clean up:**
* [x] [fix comment](https://github.com/TravelMapping/DataProcessing/blob/80f27243bf26579c53c6c7a215a5aeb22347317a/siteupdate/cplusplus/classes/TravelerList/TravelerList.h#L43-L44)
* [x] Constexpr the static edge format constants
* [x] Template specialization
* [x] As of `ecff`, cmath no longer explicitly needed in HighwayGraph.cpp
* [x] Extraneous `else` after `continue`; parens can be clarified https://github.com/yakra/DataProcessing/blob/80f27243bf26579c53c6c7a215a5aeb22347317a/siteupdate/cplusplus/classes/GraphGeneration/HighwayGraph.cpp#L112-L116
* [x] extraneous `visibility == 1` check just before that
* [x]  (**`4db4`**) `maxbits` less useful in `SimItOpt2`. Delete it; replace with `8*sizeof(unit)`; let `-1` and `+1` cancel out.
* ~`bits` should be `unsigned char` in `pun` branch. Dumb luck that it ran without errors. Fixed for `ComItOpt`.~
  Never mind. Using a branch that retains `unit` instead.
* [x] `uint8_t`etc.
* [ ] Explicit instantiation?
* [x] Inlining MV&E (`2d1b`) means `#include "../../templates/TMBitset.cpp"` not needed in HighwayGraph.h. Can lose the include guard too LOL. :cowboy_hat_face:
* [ ] `segments` SQL table: only iterate `clinched_by` for active/preview systems
* [x] (**`c8b9`**) Check for diffs due to constant folding: `8/sizeof(unit)`
* [x] Comment for `!=` and `|=` operators
* [x] Review TMBitset variable names
* [x] Cast `(unit)1` before `<<`, lest the unsigned long bug make a reappearance. See `f8cf` on `SimItOpt2` branch.
* [x] (**`4db4`**) Switch: are additions in `for` loop reordered? Make it look pretty!
* [x] nix `()` and `add_value` until needed

**Comment by yakra** [comment]
find crashes via
```sh
for file in sulogs/2023-04-06/siteupdate_{a423,4448,8fba,8d55,7828,96e9,2d1b,5c76}*; do
  echo -e "$file\t" `tail -n 1 $file
  | sed 's~\[[0-9.]*\]~~'
  | tr -d .`; done
| grep -v 'Total run time:'
| sed -r 's~.*siteupdate_(....)-.*~\1~'
| uniq
```

**Comment by yakra** [comment]
### dead branches
* `SimItOpt2` with sign bit bug before rebase:
  * `dd1b6e0` long
  * `a8a3db9` int
  * `9280ec4` short
    OK, not *dead*, but deprecated binary & logs. Rebased here; bugfix commit added

**Comment by yakra** [comment]
### commits
c | incl? | descr | comments
-- | -- | -- | --
a5a7 | yes | contig RAM    | Prerequisite for everything else
ecff | yes | TMB 1st draft | The main point of all this :)
d704 | yes | t_l via TMB   | Small speedup. Saves RAM. Potential for improvements via iteration and \|= optimizations.
a009 | yes | t_l list->vec | Not slower. The Right Thing To Do. Saves RAM. Locality. **Is index used in future commits?**
91a0 | yes | !extr include | Housekeeping
7ce7 | yes | userlog warn  | Unrelated, and doesn't appear to affect performance any, fnord. **Rebase earlier?**
f977 | yes | t_l as ref    | Safer code. No slower really. *LOL, and everything else is a child of this.*
eaa6 | no  | nix tl::tn    | Hurts performance. See `9fdc` et al instead.
4e05 | no  | avoid iterate | Child of `eaa6`. See `96e9` even though it's the same diff. :P
6922 | TBD | ctor / init   | Any changes to performance? See next commit.
5c76 | TBD | integral type | Userlogs slightly slower? Test again once dust settles?
b4ab | TBD | names & order | Arg order just makes sense. Name changes are more related to prev commit.
e61a | yes | ++u	   | No change to binary. Done on its own in some future commits.
a423 | yes | branching CBT | Faster userlogs. **Rebase earlier?**
4448 | no  | short	   | `unit` branch; affects `\|=` only. Prefer flavors with iterator optimization.
8fba | no  | int	   | `unit` branch; affects `\|=` only. Prefer flavors with iterator optimization.
8d55 | no  | long	   | `unit` branch; affects `\|=` only. Prefer flavors with iterator optimization.
7828 | no  | no-branch CBC | Hurts performance
96e9 | yes | nix tl::tn    | `4e05` cherrypicked. *Test again with optimized iteration for giggles.*
2d1b | TBD | inline mv&e   | Probably? Slight speedup? Test again after dust settles?
f28c | no  | long bugfix   | `unit` branch; affects `\|=` only. Prefer flavors with iterator optimization.
953a | TBD | ! unit param  | Not strictly necessary for pointer-punning `\|=`, but cleans things up.
03ec | TBD | punning `\|=` | Evaluate WRT straight-up unit `\|=`, and iterator optimization. **Examine** simplifying if 16/32-bit units chosen.
7958 | no? | SimItOpt1	   | SimItOpt2 will probably outperform this.
3910 | TBD | SimItOpt2	   | Evaluate all unit sizes against ComItOpt. Take into account all tasks and effects on `\|=`.
1be1 | no? | SIO1 short	   | SimItOpt2 will probably outperform this.
87e4 | no? | SIO1 int	   | SimItOpt2 will probably outperform this.
2cbb | no? | SIO1 long	   | SimItOpt2 will probably outperform this.
9280 | TBD | SIO2 short	   | Evaluate all unit sizes against ComItOpt. Take into account all tasks and effects on `\|=`.
9347 | TBD | sign bit fix  | "
acc9 | TBD | unsigned int  | "
8269 | TBD | unsigned long | "
f8cf | TBD | ulong bugfix  | "
f749 | TBD | ComItOpt	   | Evaluate against SimItOpt. All tasks. Try with per-unit `\|=`. **Try a 16-bit version.**
9fdc | TBD | trav_nums	   | May not do much on its own. Try again after other speedups are in place.
bc9d | TBD | TMB it idx    | **Pro:** No arithmetic for clinchedby_code. **Con:** Still adding b.array+index everywhere else (deref).
0b69 | TBD | iterator ptr  | **Pro:** No arithmetic for dereferencing. **Con:** CBC subtracts out.
^ ^^ |     | ^ ^^	   | Both are superior to `9fdc`, which adds for *everything*, then subtracts out for CBC. **Test both sans `9fdc`. Which gets called more?**

**Comment by yakra** [comment]
## Functions, operators, etc.
This is just a placeholder for now...

* **`insert`**
* **`operator ()`**
* **`operator !=`**
* **`operator |=`**
* **iteration**

**Comment by yakra** [comment]
## HTML (resolved)

* **TMB_Total.html**
  Original commits; not much to see here.
  Maybe do another one with the final selected commit for kicks.
* **TMB_ReadList.html**
  Original commits. No real changes to `insert`.
  Maybe do another one with the final selected commit for kicks, considering the weird minor-but-consistent diffs.
* **TMB_ConcAug.html**
  Original commits. No real changes to `insert`.
  Maybe do another one with the final selected commit for kicks, considering the weird minor-but-consistent diffs.
* **TMB_CompStatsO.html**
  Original commits, `47a7` iterator optimization, `558e` iterate active/preview only, `4db4` store & return pointer.
  Using `4db4`.
* **TMB_iter.html**
  No-build, contig TLs, t_l as ref, 4 SIO1, 4 SIO2, 8/16-bit CIO.
  Using `acc9`, 32-bit SIO2.
* **TMB_iter2.html**
  No-build, contig TLs, t_l as ref, 8/16/32-bit SIO2, 8/16-bit CIO, [bits >> 1], ternaries.
  Using `acc9`, 32-bit SIO2.
* **TMB_UserLog.html**
  Original commits, `a423` branching CBT, `bf94` merge.
  Using `bf94`.
* **TMB_Compress.html**
  Original commits; no changes to `operator !=` here.
  Maybe do another one with the final selected commit for kicks.
* **TMB_Graphs.html**
  Original commits. Refer to pages targeting the specifics: `|=`, iteration, clinchedby_code, trav_nums, inline mv&e, unit/punning.
  Using `f977` though that commit may be overwritten.
* **TMB_unit.html**
  `f977` + 3 more `unit` alternatives, `03ec` punning `|=`, 4 SIO2, 4 with 8/16/32-bit punning
  Using `47a7`, 32-bit SIO2 + 64/32-bit punning.

**Comment by yakra** [comment]
## HTML

* **TMB_CBC.html**
  `f977` t_l as ref, `eaa6` nix tl::tn, `4e05` avoid iterate, `7828` no-branch CBC, `96e9` avoid iterate (cherrypick).
  Merging `f977` and `96e9`.
  **ToDo:** `4db4` & children on `TMBPreAlpha` branch.
* **TMB_TravNums.html**
  No-build, contig TLs, t_l as ref, `9fdc` trav_nums, `bc9d` TMB it idx, `0b69` iterator ptr.
  `0b69` cherrypicked -> `4db4`.
  **TBD:** Unsure what to do WRT trav_nums yet.
* **TMB_inline\*.html**
  `f977` t_l as ref, `2d1b` inline mv&e, `4db4` store & return pointer, `2eff` merge the prev 2.
  **ToDo:** Finish lab3, lab4, bsdlab.
* **TMB_nixtl.html**
  `47a7` iterator optimization, `edb4` nix t_l, aecc "0"
  **ToDo:** lab3, `4db4` & children on `nixtl` branch.
* ***(TBD)***
  Compare best commits from `TMBPreAlpha` and `nixtl` branches.

**Comment by yakra** [comment]
### hidden/deleted branches
| comm | branch    | DoWhat | comment
|  --  |   --      |   --   | -- |
| 47a7 | 764-32    | delete | parent of TMBPreAlpha & nixtl
| c310 | 64-16     | hidden |
| 72e2 | 64-32-16  | delete | parent of 64-16
| fc17 | SIO2pun   | hidden |
| 2d94 | ternaries | hidden
| 16bb | bit1      | delete | parent of ternaries
| ec4e | ComItOpt16| delete | parent of ternaries
| 0b69 | return_p  | hidden
| bc9d | idx       | hidden
| 9fdc | nixon     | delete | parent of return_p
| f749 | ComItOpt  | delete | parent of ternaries
| f8cf | SimItOpt2 | hidden
| 2cbb | SimItOpt  | hidden
| 03ec | pun       | delete | parent of ternaries
| f28c | unit      | hidden
| 7828 | cbycode   | hidden
| 54fb | **issue588** | hidden | **use this**

**Comment by yakra** [comment]
# Alpha ToDo list

### Solo items
C | Descr | Comments
-- | -- | --
**`54fb`** | issue 588     |
**`91a0`** | !extr include |
**`7ce7`** | userlog warn  |
**`96e9`** | avoid iterate |
  _ToDo_   | Timestamp for first task (Get list of travelers in the system). Python Too.
  _ToDo_   | Constexpr the static edge format constants.
|	v  | Extraneous else after continue; parens can be clarified
|	^  | extraneous visibility == 1 check just before that

### Solo if possible; else contig RAM
C | Descr | Comments
-- | -- | --
**`4504`** | "0"     | HGEdge, HG.h, HighwaySegment. HG.cpp: master vector<*> setup.

### contig RAM group
C | Descr | Comments
-- | -- | --
  _ToDo_   | Get TMArray sorted. | TMArray<TravelerList> means threaded construction in place (via placement new) without separate read_list function.
**`a5a7`** | contig RAM    |
  _ToDo_   | fix comment
  _ToDo_   | TravelerList dtor, to delete traveler_num

### TMB group
C | Descr | Comments
-- | -- | --
**`ecff`** | TMB 1st draft | Does ctor init vars in order? Don't include siteupdate.cpp changes; see below.
  _ToDo_   | init segments with TravelerList::ids.size()
**`a423`** | branching CBT |
**`acc9`** | unsigned int  |
**`47a7`** | 64-32-bit pun |
**`4db4`** | iterator ptr  |
**`c896`** | arg order     |
**`7415`** | ctor / init   |
**`4a64`** | integral type |
**`01d6`** | reorder membr |
**`01e7`** | cbt_index     |
**`48c8`** | part add_idx  |
**`c8b9`** | const fold    |
**`6634`** | whitespace    |
**`9536`** | constexpr     |
**`ecef`** | ST aug index  |
  _ToDo_   | nix () and add_value until needed
  _ToDo_   | Cast (unit)1 before << | ...lest the unsigned long bug make a reappearance. See f8cf on SimItOpt2 branch.
  _ToDo_   | Review TMBitset variable names
  _ToDo_   | Comment for != and |= operators
  _ToDo_   | segments SQL table: only iterate clinched_by for active/preview systems
  _ToDo_   | uint8_tetc.
  _ToDo_   | Template<br>specialization
  _ToDo_   | Explicit instantiation?

### t_l via TMB group
C | Descr | Comments
-- | -- | --
**`d704`** | t_l via TMB   |
  _ToDo_   | As of d704, cmath no longer explicitly needed in HighwayGraph.cpp
**`2d1b`** | inline mv&e   |
  _ToDo_   | Don't include TMBitset
**`4504`** | "0"     | GetSubData. HG.cpp: master case 1, assign traveler numbers, 3 size->travnum, tmg_line.
**`7f87`** | trav     |
**`a009`** | t_l list->vec |

**Comment by yakra** [comment]
partial specialization experiments
deleted stash @ 484be5074e68f31db790cc53b34cf2494f6ff114

**Comment by yakra** [comment]
Benchmark commits:
* WIP:
  `HD @ 59afa75`
  `UD @ 2126e76`
* Final:
  `HD @ 40c2356`
  `UD @ 5b071e5`

**Comment by yakra** [comment]
![List](https://github.com/yakra/DataProcessing/assets/13720877/b2c9d361-18fd-401d-8c28-42b009dc50b2)

![Conc](https://github.com/yakra/DataProcessing/assets/13720877/16090864-4cff-4dae-a926-a63381b3e8ce)
![Stat](https://github.com/yakra/DataProcessing/assets/13720877/146fad73-ac0a-45fc-96ff-49503a395c38)
![User](https://github.com/yakra/DataProcessing/assets/13720877/eafb873d-6657-4cc0-b474-d2f5039ab0db)
![Comp](https://github.com/yakra/DataProcessing/assets/13720877/f10fbc9e-601f-4692-a0dd-ef2b81b88211)
![Graph](https://github.com/yakra/DataProcessing/assets/13720877/2d0d8b13-1a2f-421b-931d-fce2890a4872)
![Graph_Linux](https://github.com/yakra/DataProcessing/assets/13720877/387c8c24-a7a1-4c01-8e9a-944bda088374)
![Total](https://github.com/yakra/DataProcessing/assets/13720877/59bd48ea-ad34-4782-ac59-b716f31eb0d7)

**Comment by yakra** [comment]
## deleted branches (BiggaTomato)
![g_db](https://github.com/yakra/DataProcessing/assets/13720877/639315f0-9d97-4c90-b65c-f5f374a75987)
* **g_db** comments out DB [here](https://github.com/yakra/DataProcessing/blob/80f27243bf26579c53c6c7a215a5aeb22347317a/siteupdate/cplusplus/siteupdate.cpp#L582-L588) and [here](https://github.com/yakra/DataProcessing/blob/80f27243bf26579c53c6c7a215a5aeb22347317a/siteupdate/cplusplus/siteupdate.cpp#L599-L610).
* **g_trav** comments out everything specific to traveled graphs in mv&e, write_master and write_sub, except for assigning traveler numbers. HighwayGraph.cpp only.
* **g_cb** comments out [`traveler_lists` population](https://github.com/yakra/DataProcessing/blob/80f27243bf26579c53c6c7a215a5aeb22347317a/siteupdate/cplusplus/classes/GraphGeneration/HighwayGraph.cpp#L270-L274)
* **`990a288`** adds `{}//` at the beginning of [this line](https://github.com/yakra/DataProcessing/blob/80f27243bf26579c53c6c7a215a5aeb22347317a/siteupdate/cplusplus/classes/HighwaySegment/HighwaySegment.cpp#L74)
