### ISSUE TITLE
Graph generation: next steps forward

### ISSUE THREAD

**Issue by yakra** [yakra/DataProcessing#270]
**Setup**
* [ ] #269
* [ ] #265 Phase 1

**Subgraph efficiency, lightweight**
* [ ] Either [use](https://github.com/TravelMapping/DataProcessing/issues/589#issuecomment-1533942362) or https://github.com/TravelMapping/DataProcessing/issues/589
* [ ] [unique_name -> char*](https://github.com/TravelMapping/DataProcessing/issues/518#issue-1206431350)
* [ ] [GLE region/system lists -> vectors](https://github.com/TravelMapping/DataProcessing/issues/518#issuecomment-1481135685)
* [ ] #264
* [ ] TravelMapping#613

**Subgraph efficiency, heavyweight**
* [ ] #251
* [ ] [TMBitset<HGEdge*>](https://github.com/TravelMapping/DataProcessing/issues/518#issuecomment-1418233143)
